
#+TITLE: PyAPL
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [letterpaper]
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER:\hypersetup{colorlinks, citecolor=violet, linkcolor=red, urlcolor=blue} 
#+OPTIONS: toc:nil
(Partial) Implmentation of [[https://aplwiki.com/wiki/Main_Page][APL]] on top of Python--Python APL EDSL

School Project, Dec 2021.

* Core Design
** APL Array
The ~APLArray~ object is the core part of this implementation. Unlike typical N-dementional list in Python, which 
literally puts lists inside of lists N times to accomplish, APLArray seperates the demention from it's data. This means
that it keeps two arrays, one for data and other for it shape. This has to be done because the "typical" N-dementional list
in python have no capability to extract its shape (in a sane way), no easy way to transform shapes, and provided not enough 
abstractions. 

Later, turns how this way of showing N-dementional Array in used in [[https://code.jsoftware.com/wiki/Essays/Incunabulum][Arther Witney's original one-page interpreter]], K Language, a modern APL dialect, and 
also by Numpy. 


In Arther Witney's original one-page interpreter, 
#+begin_src c
  typedef struct a{I t,r,d[3],p[2];}*A;
#+end_src
is almost equivlant to this project's ~APLArray~ object: ~d~ is data, ~r~ is rank, ~p~ is shape; 
~.arr~ is data, ~len(.shape)~ is rank, ~.shape~ is shape in ~APLArray~.

Arther Witney's terse C code is very cryptic, but, thankfully, I was able to understand his implmentation of 
Array. 

It's a big suprise as I did not researched the implementations of vector programming language in
forehand, yet still yielded similar fundumental implmentations.

** Dy/Monadic function
Monad here is not [[https://wiki.haskell.org/Monad][Monad from the Type Theory]] that provides binding operations. Monad in APL means an operator
with only single inputs Array. So ~* 5~ is a monadic use of ~*~ operator; it will return ~e^5~. 

Dyadic, as its name implys, have two inputs Arrays, from left and right. So ~2 * 5~ is a dyadic use
of ~*~ operator; it will return ~2^5~. 

As shown, most of APL Operators can be used both monadically and dyadically. For example, ~÷~ is
reciprocal monadically and divide dyadically; ~⌽~ is "Reverse" monadically and "Rotate" dyadically; and 
~↓~ is "Split" monadically and "Drop" dyadically. 

Thanks to the flexibility of Python functions and optional arguments, APL Operators was implmented
cleanly in one symbol like those of APL. 

* Concurrency
An attempts to implement concurrent operations in the Core indexing function and Array operators was made, but most of the
operations were bottlenecked by the BinOperations, by the fact that Python does not support Tail Recursion Optimization, and by
the delay on pool allocation. There were no improvements in the performance; rather, it mostly harmed the performance. 

There was a brief consideration of implementing core in C with ffi interfacing, but the ctype and cffi documentation
proved itself to be a great pain; struggling in untyped maddness of Python was enough for me.

So, at this point, there is nothing can be done over the matter of performance. It is just a comprehensive implementation 
of APL (partial) as a Python EDSL. Personally, if it was implemented in more strongly typed and static language with matured 
supports over optimization of recursive calls, the performance would have been tolerable. 

* Applications
Like traditional APL, PyAPL provides convenience on manupulating complex data by providing
framework for array operations like inner products, outer products, rotate, and drop. 

Long, uncomprehensive and overly verbose code that does simple data manupulation is only hindering one
from understanding the tasks code does. APL, on the other hand, compresses these operations
and it expressive to the readers. This EDSL provides same expressive operations on top of pure
Python, allowing one to write same terse code in Python. 


Famous [[https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life][Conway's Game of Life]] is implemented in
PyAPL as ~Example_GameOfLife.py~ as an example. Again, it is pretty slow: each generations takes =~0.1 Seconds=. But, nothing can be done. 

Other simple examples, like Average of an array, can be found on APL wiki, then be translated into PyAPL.

Generally, PyAPL can be used in many cases where one has to manupulate data. For example, extracting data
from variable data formats, like csv, json, xml, and turning pure data into useful forms of data
through serise of Array operations provided in PyAPL.

* Tests
Some test cases are provided in ~test_APL.py~ with some array operations and type checkings. Sadly, did not
have enough time to generate longer test cases, but it will do the job for now. 

* Note
Codes are written using recursion, mapping; the code is very dense in it's operation. 
The few functions defined in the top, fmap, reduce, zipWith, flatten, indexs, and more, are used heavily
on almost all operations and is essential on understanding the major operations in the entire project.

Note how entire operations were programed without any utilization of loops.
Without conventional looping and simple function calls, It might seem uneffective and cryptic, but
they allows program to maintain mostly stateless and reproducable always.



* More Examples
** Reshape
#+begin_src python :exports both :results output
  from APL import *
  print(Rho([3, 3],Iota(5)))
#+end_src

#+RESULTS:
: ┌3,3──┐
: │1 2 3│
: │4 5 1│
: │2 3 4│
: └─────┘

** Average
#+begin_src python :exports both :results output
  from APL import *
  a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  print(Divi(Reduce(Plus, a), len(a)))
#+end_src

#+RESULTS:
: 5.50

** Rotate
Rotates first axis with -1 direction and second axis with 2 direction
#+begin_src python :exports both :results output
  from APL import *
  a = Rho([3, 3], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
  print(Rotate([-1, 2], a))
#+end_src

#+RESULTS:
: ┌3,3──┐
: │9 7 8│
: │3 1 2│
: │6 4 5│
: └─────┘

** Occurence of Characters
#+begin_src python :exports both :results output
  from APL import *
  a = Plus(96, Iota(26)).mapAll(chr) # all alphabet characters
  b = list("bananafish") # given string
  print(a)
  print(Reduce(Plus, JotDot(Eq)(a, b)))
#+end_src

#+RESULTS:
: a b c d e f g h i j k l m n o p q r s t u v w x y z
: 3 1 0 0 0 1 0 1 1 0 0 0 0 2 0 0 0 0 1 0 0 0 0 0 0 0
